# .github/workflows/deploy-pages.yml
name: Deploy to GitHub Pages (artifact flow)

on:
  push:
    branches: [ main ]          # main 브랜치에 푸시될 때마다 실행

permissions:                    # Pages-deploy에 필수!
  contents: read                # 소스 읽기
  pages: write                  # Pages 퍼블리시 권한
  id-token: write               # OpenID 연결 (deploy-pages)

concurrency:                    # 병렬 배포 충돌 방지
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) Node 설정 (npm 캐시 포함)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3) 의존성 설치 & 빌드
      - run: npm ci
      - run: npm run build && npm run export     # ./out 생성

      # 4) Pages용 아티팩트 업로드
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out                            # 정적 산출물 위치

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 5) 업로드된 아티팩트를 Pages에 배포
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
